from pathlib import Path
path = Path('src/pages/Admin.tsx')
text = path.read_text(encoding='utf-8', errors='ignore')
old = "  const fetchUsers = async () => {\r\n    try {\r\n      const { data, error } = await supabase.rpc('get_all_users_for_admin');\r\n      \r\n      if (error) throw error;\r\n      setUsers(data || []);\r\n    } catch (error) {\r\n      console.error('Error fetching users:', error);\r\n      toast({\r\n        title: 'Erro',\r\n        description: 'Nǜo foi poss��vel carregar os usuǭrios',\r\n        variant: 'destructive',\r\n      });\r\n    }\r\n  };\r\n"
new = "  const fetchUsers = async () => {\r\n    try {\r\n      const rpcResponse = await supabase.rpc('get_all_users_for_admin');\r\n      \r\n      if (!rpcResponse.error) {\r\n        setUsers(rpcResponse.data || []);\r\n        return;\r\n      }\r\n\r\n      console.warn(\r\n        'get_all_users_for_admin RPC failed, falling back to profiles query',\r\n        rpcResponse.error\r\n      );\r\n\r\n      const fallback = await supabase\r\n        .from('profiles')\r\n        .select('id, email, whatsapp, is_admin, is_founder, founder_price, created_at');\r\n\r\n      if (fallback.error) {\r\n        throw fallback.error;\r\n      }\r\n\r\n      const mappedUsers: User[] =\r\n        (fallback.data ?? []).map((profile: any) => ({\r\n          user_id: profile.id,\r\n          email: profile.email ?? '',\r\n          whatsapp: profile.whatsapp ?? '',\r\n          is_admin: profile.is_admin ?? false,\r\n          is_founder: profile.is_founder ?? false,\r\n          founder_price: profile.founder_price ?? null,\r\n          plan_name: null,\r\n          plan_id: null,\r\n          subscription_status: null,\r\n          created_at: profile.created_at ?? new Date().toISOString(),\r\n          custom_games_count: 0,\r\n        }));\r\n\r\n      setUsers(mappedUsers);\r\n    } catch (error) {\r\n      console.error('Error fetching users:', error);\r\n      toast({\r\n        title: 'Erro',\r\n        description: 'Não foi possível carregar os usuários',\r\n        variant: 'destructive',\r\n      });\r\n    }\r\n  };\r\n"
if old not in text:
    raise SystemExit('Original fetchUsers block not found. Aborting replacement.')
text = text.replace(old, new)
path.write_text(text, encoding='utf-8')
print('fetchUsers block updated')
